export const RegisterAccounts = {
  'testing-2': { email: 'testjakarta02@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-3': { email: 'testjakarta03@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-4': { email: 'testjakarta04@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-5': { email: 'testjakarta05@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-6': { email: 'testjakarta06@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-7': { email: 'testjakarta07@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-8': { email: 'testjakarta08@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-9': { email: 'testjakarta09@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-10': { email: 'testjakarta10@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-11': { email: 'testjakarta11@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-12': { email: 'testjakarta12@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-13': { email: 'testjakarta13@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-14': { email: 'testjakarta14@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-15': { email: 'testjakarta15@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-16': { email: 'testjakarta16@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-17': { email: 'testjakarta17@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-18': { email: 'testjakarta18@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-19': { email: 'testjakarta19@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-20': { email: 'testjakarta20@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-21': { email: 'testjakarta21@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-22': { email: 'testjakarta22@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-23': { email: 'testjakarta23@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-24': { email: 'testjakarta24@kbmapp.com', password: 'pisanggoreng0987' },
  'testing-25': { email: 'testjakarta25@kbmapp.com', password: 'pisanggoreng0987' },
} as const;
